title: Deploying AI/ML applications on LUMI in Life Science domain

plugins:
  - jekyll-sitemap

collections:
   hands-on:
        output: true

defaults:
  -
    scope:
      path: "_hands-on"
    values:
      layout: "default"
